### ISSUE TITLE
checkpoint - code mismatch

### ISSUE THREAD

**Issue by georgesterpu** [cmusphinx/g2p-seq2seq#101]
Hi
Just cloned the repo a few minutes ago, ran the setup script and downloaded the pre-trained model.
Launching g2p-seq2seq crashes with the following message:

`NotFoundError (see above for traceback): Key embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/Attention_0/bias not found in checkpoint
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]`

Has the code has been updated after releasing the pre-trained model ?

**Comment by nurtas-m** [comment]
Hello!
Do you launch the g2p-seq2seq project on a master branch? What is your current tensorflow version?

In a few hours we will deploy project from t2t branch to the master branch.

**Comment by georgesterpu** [comment]
Hi @nurtas-m 
Indeed, I've cloned the master branch, and I'm using TensorFlow 1.6.
Has the published model been trained using the code on the t2t branch ?

**Comment by georgesterpu** [comment]
I see, thanks. Will wait for your update when it's ready. Thank you for making available this useful project.
