### ISSUE TITLE
Decoder gives error for symbols which were not present in training data.

### ISSUE THREAD

**Issue by mausamj1992** [cmusphinx/g2p-seq2seq#113]
In the "stop_criteria" branch code, while decoding, the error saying "keyerror["#"]" arises as this symbol "#" was not present in my training data.
Specifically, in line number 76 in "g2p_encoder.py", self._sym_to_id[sym] is the cause of error as it can find no id for a symbol.
In this case, shouldn't the decoder emit "UNK" token instead of giving error ?

**Comment by nurtas-m** [comment]
@nshmyrev , what do you think about this option?

**Comment by nshmyrev** [comment]
Decoder should ignore unknown symbols and print warnings about them.

**Comment by nurtas-m** [comment]
Fixed with commit: https://github.com/cmusphinx/g2p-seq2seq/commit/c21fd791fcb8e841fc0b9c2d928a8a017970ecd9

**Comment by mausamj1992** [comment]
Thank you !
