### ISSUE TITLE
g2p-seq2seq --interactive --model model_folder_path

### ISSUE THREAD

**Issue by RamTex** [cmusphinx/g2p-seq2seq#152]
**My error**
(venv) developer@ubuntu:~/Desktop/sphinx-source$ g2p-seq2seq --interactive --model_dir /home/developer/Desktop/sphinx-source/pocketsphinx/model/
Traceback (most recent call last):
  File "/home/developer/.local/bin/g2p-seq2seq", line 7, in <module>
    from g2p_seq2seq.app import main
  File "/home/developer/.local/lib/python2.7/site-packages/g2p_seq2seq/__init__.py", line 24, in <module>
    from g2p_seq2seq import app
  File "/home/developer/.local/lib/python2.7/site-packages/g2p_seq2seq/app.py", line 31, in <module>
    from g2p_seq2seq.g2p import G2PModel
  File "/home/developer/.local/lib/python2.7/site-packages/g2p_seq2seq/g2p.py", line 28, in <module>
    from g2p_seq2seq import g2p_trainer_utils
  File "/home/developer/.local/lib/python2.7/site-packages/g2p_seq2seq/g2p_trainer_utils.py", line 26, in <module>
    from tensor2tensor.utils import input_fn_builder
**ImportError: cannot import name input_fn_builder**

**Additional information:**
(venv) developer@ubuntu:~/Desktop/sphinx-source$ python --version
Python 2.7.15rc1
(venv) developer@ubuntu:~/Desktop/sphinx-source$ pip --version
pip 18.0 from /home/developer/tensorflow/venv/local/lib/python2.7/site-packages/pip (python 2.7)
(venv) developer@ubuntu:~/Desktop/sphinx-source$ virtualenv --version
15.1.0
(venv) developer@ubuntu:~/Desktop/sphinx-source$ pip list | grep tensor
tensor2tensor            1.9.0    
tensorboard              1.10.0   
tensorflow               1.10.1   
tensorflow-gpu           1.10.1 

Any ideas?

**Comment by nshmyrev** [comment]
Tensorflow version mismatch

**Comment by RamTex** [comment]
Ok, thanks do far.

Got same error with:
tensor2tensor            1.9.0    
tensorboard              1.6.0    
tensorflow               1.6.0    
tensorflow-gpu           1.10.1 

and with:
tensor2tensor            1.9.0    
tensorboard              1.6.0    
tensorflow               1.7.0rc0 
tensorflow-gpu           1.10.1


andbody a running setup can post version numbers of every involved component?
