### ISSUE TITLE
p2g (solving inverse problem)

### ISSUE THREAD

**Issue by MuireannMacCarthy** [cmusphinx/g2p-seq2seq#176]
Hi,

Running the G2P in interactive mode works perfectly but I'm having issues using --p2g to solve the problem in reverse.

I'm training the model on the CMU dict linked on this repo underneath the "Training G2P" section.

However when I run the command below:

g2p-seq2seq --train cmudict.dict --model_dir /c/Users/mmacc/OneDrive/Documents/g2p-seq2seq/ --p2g --cleanup

I get all sorts of errors, see below:

![p2gerror1](https://user-images.githubusercontent.com/31772318/57372083-90c99180-718c-11e9-952c-0952f103e664.JPG)

![p2gerror2](https://user-images.githubusercontent.com/31772318/57372093-97f09f80-718c-11e9-8bc8-cf3057714053.JPG)

Any suggestions on where I'm going wrong would be very helpful,

Thanks

**Comment by MuireannMacCarthy** [comment]
Problem is resolved for me, if you received similar error continue reading for solution.

g2p-seq2seq --train cmudict.dict --model_dir /c/Users/mmacc/OneDrive/Documents/g2p-seq2seq/ --p2g --cleanup

The cmudict.dict reference from the above command is stored in the same directory from which the command was executed so I did not include entire file path. However replacing cmudict.dict with its complete path worked for me. See below:

g2p-seq2seq --train /path/to/cmudict.dict --model_dir /c/Users/mmacc/OneDrive/Documents/g2p-seq2seq/ --p2g --cleanup

**Comment by zhushaojin** [comment]
hi,I ran into the same issue.
However when I fed the whole path of cmudict.dict, the error still occured.
The command line I used is:
`g2p-seq2seq --train /data00/home/***/anaconda3/bin/cmudict.dict --model_dir g2p-seq2seq-model-6.2-cmudict-nostress --p2g --cleanup`
The error is

> WARNING:tensorflow:Invalid symbol:zavada
> WARNING:tensorflow:Invalid symbol:A
> WARNING:tensorflow:Invalid symbol:H
> WARNING:tensorflow:Invalid symbol:z
