### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by FrancescoLimoni** [cmusphinx/g2p-seq2seq#188]
Hello everyone,

I am trying to using the g2p-seq2seq in order to train my dictionary to new words that are not present at the moment. I have been follow step by step the installation of tensorFlow and tesor2tensor. I got stock for couple of day before I realize that Python3  was needed in order to install and run those libraries. Now once again I am stuck at the Sequence-to-Sequence G2P toolkit installation process. When I am  running _**$ sudo python setup.py install**_ I got back this error 

_**Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools**_

I already installed the setuptools executing  _**$ pip install setuptools**_ command line without any problem, but the issue persists. Is anyone know how to solve this issue? 

I don't if this information would be useful to know but I am using a macbook running macOS Catalina 10.15.4 with Phyton3, Pip3 and  Braw installed 

Thank you in advance 
Francesco

**Comment by nshmyrev** [comment]
Most likely you have multiple python installations in your system. You can figure that out with `which python` and `which pip`. Most ikely you need to run `python3 setup.py install` instead of `python setup.py install`.

**Comment by FrancescoLimoni** [comment]
@nshmyrev Thank you I follow a tutorial this morning in which I should have set as default Python3 instead Python2.7 but obviously not successfully because running the command with Python3 solved the issue!
