### ISSUE TITLE
Issues Running G2P

### ISSUE THREAD

**Issue by FrancescoLimoni** [cmusphinx/g2p-seq2seq#189]
Hello everyone, 

I successfully install everything that i need in order to use the Sequence-to-Sequence G2P toolkit. 

Now I was trying to execute this command _**$ g2p-seq2seq --interactive --model_dir model_folder_path**_
but I getting back this message _**zsh: /Users/francescolimoni/Desktop/Mat g2p/venv/bin/g2p-seq2seq: bad interpreter: "/Users/francescolimoni/Desktop/Mat: no such file or directory**_ . From my understanding I miss one or more files. Can anyone explain me little bit more how that works and specially what do I need the _**g2p-seq2seq-model-6.2-cmudict-nostress**_  folder for? 

I am quite sure I need to do something with it but I am having hard time to understand how the tutorial works. I think sometime it skips or take some informations for granted when they are not.

Thank you
Francesco

**Comment by nshmyrev** [comment]
The error is due to the space in file path between Mat and g2p.

> what do I need the g2p-seq2seq-model-6.2-cmudict-nostress folder for

Model in machine learning is a data structure which is created on a train data and used to compute the results. You can learn about it from any machine learning introduction.
