### ISSUE TITLE
Write a unit test with small dataset

### ISSUE THREAD

**Issue by nshmyrev** [cmusphinx/g2p-seq2seq#26]
Create a toy dictionary with 20 lines and train an g2p model with 2 elements on hidden layer.

**Comment by nurtas-m** [comment]
Fixed with commit ae999cbecea267312ea3ffc353d133dee6a99593

**Comment by nshmyrev** [comment]
Add tests for decoding

**Comment by nshmyrev** [comment]
Dictionary should use 3 letters. Accuracy on evaluation should be non-zero.

**Comment by nshmyrev** [comment]
Tests should verify results. Decoding test should verify the result of decoding. Evaluation test should evaluate returned accuracy.

**Comment by nshmyrev** [comment]
Still some issues
