### ISSUE TITLE
test accuracy with trained model

### ISSUE THREAD

**Issue by sonamsingh19** [cmusphinx/g2p-seq2seq#32]
I want to test accuracy of the trained model on cmudict.
Are there any standard training, validation, test dict for this task. 

How it is compared in papers for fair evaluation if there are no standard partitions?
Thanks a lot for this code.

**Comment by gorinars** [comment]
To me it seems that some papers use their own partitioning. 
To compare the performance, it is best to run some state-of-the-art rG2P system like phonetizaurus.

**Comment by sonamsingh19** [comment]
Thanks. I am new to this are and comes from deep learning side .

**Comment by gorinars** [comment]
No problem. We will try to make you run this thing properly in your other ticket. It should work nicely

**Comment by nshmyrev** [comment]
There is actually a reference dictionary here, I've just uploaded to our downloads, see

https://github.com/cmusphinx/g2p-seq2seq/issues/36
