### ISSUE TITLE
Where is the Train Model file?

### ISSUE THREAD

**Issue by G10DRAS** [cmusphinx/g2p-seq2seq#37]
I used the following command to train G2P model:
`python g2p.py --train /home/cmudict.dict --model /home/MyModel  --max_steps 8400`

here is the log:
```
Preparing G2P data
Creating vocabularies in /home/MyModel
Creating vocabulary /home/MyModel/vocab.phoneme
Creating vocabulary /home/MyModel/vocab.grapheme
Reading development and training data.
Creating 2 layers of 64 units.
........
Reading model parameters from /home/MyModel/translate.ckpt-8200
global step 8400 learning rate 0.4901 step-time 3.43 perplexity 1.37
  eval: bucket 0 perplexity 1.46
  eval: bucket 1 perplexity 1.29
  eval: bucket 2 perplexity 1.47
Training process stopped.
Beginning calculation word error rate (WER) on test sample.
WER :  0.4961492891
Accuracy :  0.5038507109
```
In MyModel directory there are so many generated files present, but there is no "model" file.

```
translate.ckpt-200
translate.ckpt-200.meta
translate.ckpt-400
translate.ckpt-400.meta
translate.ckpt-600
translate.ckpt-600.meta
translate.ckpt-7200
translate.ckpt-7200.meta
translate.ckpt-7400
translate.ckpt-7400.meta
translate.ckpt-7600
translate.ckpt-7600.meta
translate.ckpt-7800
translate.ckpt-7800.meta
translate.ckpt-8000
translate.ckpt-8000.meta
translate.ckpt-8200
translate.ckpt-8200.meta
translate.ckpt-8400
translate.ckpt-8400.meta
model.params
vocab.phoneme
vocab.grapheme
translate.ckpt-8600
translate.ckpt-8600.meta
translate.ckpt-8800
checkpoint
translate.ckpt-8800.meta
```
Where to get that "model" file.
or do I have to rename file `translate.ckpt-8800` to `model` ?

**Comment by nurtas-m** [comment]
Yes, "model" file is that one with maximum index. I do not recommend you to rename the model file, because the program can recognize necessary model file from all generated ones by path indicated in "checkpoint"-file. So, if you rename model file, it will be necessary to modify "checkpoint"-file too. 

I modified script to save only last model with name "model". Please pull the update.

Thank you

**Comment by G10DRAS** [comment]
Thank you @nurtas-m.
