### ISSUE TITLE
Float divison by zero

### ISSUE THREAD

**Issue by faizann24** [cmusphinx/g2p-seq2seq#43]
g2p-seq2seq --evaluate NEWARABIC/test.wordlist --model NEWARABIC
Creating 2 layers of 64 units.
Reading model parameters from NEWARABIC
Beginning calculation word error rate (WER) on test sample.
Words : 0
Errors: 0
Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 9, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 81, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 348, in evaluate
ZeroDivisionError: float division by zero

When I decode the same wordlist, it works fine.

**Comment by nshmyrev** [comment]
Evaluate takes a dictionary, not the word list

**Comment by faizann24** [comment]
Ooops. Sorry.

**Comment by nshmyrev** [comment]
Ok, thank you for the report. I added more meaningful error message for your case.
