### ISSUE TITLE
Supported languages.

### ISSUE THREAD

**Issue by ahmedalbakiri** [cmusphinx/g2p-seq2seq#53]
Does it support arabic language, if not what  alternative method could be used for text to phoneme for arabic text?

**Comment by nshmyrev** [comment]
It does support Arabic.

**Comment by ahmedalbakiri** [comment]
Thanks,
can I input like this text  بِسْمِ , I mean with diacritical marks ?

2016-10-18 1:16 GMT+03:00 Nickolay V. Shmyrev <notifications@github.com>:

**Comment by nshmyrev** [comment]
Yes, you can, you only need sufficient data for training the model.
