### ISSUE TITLE
Train a Dictionary for German Language

### ISSUE THREAD

**Issue by gkm2709** [cmusphinx/g2p-seq2seq#56]
Hello,

I am trying to add a few words to a model which I downloaded from your distributions named 

cmusphinx-cont-voxforge-de-r20161117

The words are German with characters ä ö ü etc.

I saw your tutorial at http://cmusphinx.sourceforge.net/wiki/tutorialdict about building the dictionary and went to the section to extend the dictionary. I beleive that since I have the model "cmusphinx-cont-voxforge-de-r20161117" i only need to extend it. I encountered two commands as below.

g2p-seq2seq --decode your_wordlist --model model_folder_path
g2p-seq2seq --train train_dictionary.dic --model model_folder_path

My understanding is that the commands are needed to get the phonetic transcription of the words. Then manually add it my dictionary and then train the model with this new dictionary. For this I need a model of German language to generate the transcription. I can only find an English model given on your website. Moreover, even if i have another way to generate the phonetic transcription I still need it to train. I also cannot go ahead with bootstrapping a model from the scratch as I don't have enough training data.

Maybe my understanding of the process is wrong or that i cannot locate the model which is available somewhere. Please help to get it done as there are some words which not in the dictionary i am using and these words are most critical to the performance.

Thanks in advance.

**Comment by nshmyrev** [comment]
>  I downloaded from your distributions named cmusphinx-cont-voxforge-de-r20161117

You downloaded this model from 
http://goofy.zamia.org/voxforge/de, not from our website. 

> I believe that since I have the model "cmusphinx-cont-voxforge-de-r20161117" i only need to extend it.

This archive does not have g2p model to extend the dictionary. You have to train g2p model with g2p-seq2seq or with sequitur-g2p. Pretrained sequitur-g2p model can be downloaded here: http://goofy.zamia.org/voxforge/de/sequitur-voxforge-de-r20161117.gz, but sequitur is not easy to use.

> I encountered two commands as below.

```
g2p-seq2seq --decode your_wordlist --model model_folder_path
g2p-seq2seq --train train_dictionary.dic --model model_folder_path
```

The correct order is reverse, you first train the model, then decode with it.

> My understanding is that the commands are needed to get the phonetic transcription of the words. Then manually add it my dictionary and then train the model with this new dictionary. For this I need a model of German language to generate the transcription. I can only find an English model given on your website. Moreover, even if i have another way to generate the phonetic transcription I still need it to train. I also cannot go ahead with bootstrapping a model from the scratch as I don't have enough training data.

You need to understand three basic concepts - acoustic model, language model and the dictionary. You can learn about them in our tutorial http://cmusphinx.sourceforge.net/wiki/tutorialconcepts. To include new words in recognizer you need to 

1. Add them to the dictionary with g2p model or manually http://cmusphinx.sourceforge.net/wiki/tutorialdict
2. Add them to the language model  http://cmusphinx.sourceforge.net/wiki/tutoriallmadvanced
