### ISSUE TITLE
Training a previous model further

### ISSUE THREAD

**Issue by j0ma** [cmusphinx/g2p-seq2seq#59]
Hello, 

Is there a way to take an existing model and train it further for `max_steps` iterations?

For example, running something like

```
g2p-seq2seq --train train.dic --model path/to/my_model --max_steps 20000
```

produces a message along the lines of

```
Reading model parameters from path/to/my_model
Model already exists in path/to/my_model.
```

Is there a way to simply "resume" training on the same model, without having to start training with a completely new set of weights?

**Comment by nshmyrev** [comment]
Fixed with 5e7a9af7b8a3dc2e1a1f43ab6315299257582e3e, thank you for the report!
