### ISSUE TITLE
Update to tensorflow 1.0

### ISSUE THREAD

**Issue by nshmyrev** [cmusphinx/g2p-seq2seq#64]
Time to update

**Comment by nshmyrev** [comment]
You need to update to new API, not to legacy one.

**Comment by petronny** [comment]
I get [#8191](https://github.com/tensorflow/tensorflow/issues/8191) with tf 1.1.0.rc1.213.g9dc6c17797 on Archlinux.
Please help solving this.

**Comment by nurtas-m** [comment]
Closed, because it is fixed.
