### ISSUE TITLE
Pretrained model does not work with tensorflow 1.0

### ISSUE THREAD

**Issue by nelson-liu** [cmusphinx/g2p-seq2seq#65]
Hi!
It seems like the pretrained LSTM model linked in the readme (at [sourceforge](https://sourceforge.net/projects/cmusphinx/files/G2P%20Models/g2p-seq2seq-cmudict.tar.gz/download)) does not work with tensorflow 1.0. Would it be possible to get a new upload / new link?

Thanks!

**Comment by nurtas-m** [comment]
Hello!
Yes, we will add new pretrained model soon.

Thank you!

**Comment by nshmyrev** [comment]
https://sourceforge.net/projects/cmusphinx/files/G2P%20Models/g2p-seq2seq-cmudict.tar.gz/download has been updated.

**Comment by nelson-liu** [comment]
thank you!

**Comment by xushenkun** [comment]
@nshmyrev, the pretrained model does not work with tf 1.4. Would you please add newest pretrained model. Thanks!
