### ISSUE TITLE
Raise error if model path is not specified in training

### ISSUE THREAD

**Issue by gorinars** [cmusphinx/g2p-seq2seq#67]
Currently if user forgot model path, training is going, but the model is not saved

Alternatively we should define a default path

**Comment by nshmyrev** [comment]
We implemented that for training unit test I believe, we need to think how to test properly then.

**Comment by nshmyrev** [comment]
What is 'model direction'?

**Comment by nurtas-m** [comment]
It's a direction where a user suppose to save or restore a model.

**Comment by gorinars** [comment]
Yes, we should also check if unit test works with such fix. Maybe for the moment raising WARNING would be more correct

**Comment by nshmyrev** [comment]
Fixed now
