### ISSUE TITLE
Can't train model

### ISSUE THREAD

**Issue by spate141** [cmusphinx/g2p-seq2seq#8]
- Can't train model
- Words pronunciation are wrong (using default [CMUSphinx G2P model](https://sourceforge.net/projects/cmusphinx/files/G2P%20Models/g2p-seq2seq-cmudict.tar.gz/download))

**Comment by gorinars** [comment]
For your second issue there is a bug with model file names. We will fix it shortly.

However, for the first issue on training, could you provide us with some details? What command do you run and which error you get?

**Comment by spate141** [comment]
- First issue, word pronunciation : **solved**,
- Second issue, train model: : **solved**

I am using this command in AWS G2 instance. With latest update, it's working now. Thanks!

`python g2p.py --train my_dict.dict --model temp_model --max_steps 15000 --size 512 --num_layers 3 --learning_rate 0.5`
