### ISSUE TITLE
Tutorial for translation using seq2seq api.

### ISSUE THREAD

**Issue by PratsBhatt** [cmusphinx/g2p-seq2seq#82]
I did find a wiki page describing the translation problem and experiences using seq2seq.
Can this code be made available to do a dry run?
Thanks for the info. Nice work!

**Comment by nshmyrev** [comment]
Not sure which code are you looking for, you need to explain more.

**Comment by PratsBhatt** [comment]
Thank you so much for your prompt reply. 
If you see the link https://github.com/Microsoft/CNTK/wiki/Sequence-to-Sequence-%E2%80%93-Deep-Recurrent-Neural-Networks-in-CNTK-%E2%80%93-Part-2
You would find a wiki page explaining a translation problem (English to French) by William Darling.
In this wiki he has shared his experiences but I am looking for the code or tutorial to reproduce the results mentioned by him.

**Comment by nshmyrev** [comment]
I do not think it is related to our project.

**Comment by PratsBhatt** [comment]
Oh, this wiki is in the CNTK project isn't it?
I am confused. Sorry!
