### ISSUE TITLE
Mapping phonemes to the corresponding graphemes

### ISSUE THREAD

**Issue by MahirEusufzai** [cmusphinx/g2p-seq2seq#86]
Is it feasible to show which phonemes represent which segment of each word?

For example, instead of the output being 
> tensorflow
T EH N S AO R F L OW

it would be
> tensorflow
t - T 
e - EH 
n - N 
s - S
o -  AO
r -  R
f -  F
l -  L
ow -  OW

**Comment by nshmyrev** [comment]
There is no exact mapping in seq2seq, but there are attention weights which are shifting from start to end, by learning the weights you can see what phoneme was derived from which chunk of the input string. One has to modify the seq2seq code to retrieve them though, see for details:

https://stackoverflow.com/questions/40601552/visualizing-attention-activation-in-tensorflow

**Comment by nshmyrev** [comment]
See also https://github.com/tensorflow/tensorflow/issues/1668
