### ISSUE TITLE
g2p-seq2seq cannot find tensorflow

### ISSUE THREAD

**Issue by bchinnari** [cmusphinx/g2p-seq2seq#87]
I installed tensorflow with **virtualenv** as given in
 [https://www.tensorflow.org/install/install_linux#InstallingVirtualenv](url)

When I try to install g2p-seq2seq tool using "sudo python setup.py install", the following error is popping
Searching for tensorflow>=1.0.0
Reading https://pypi.python.org/simple/tensorflow/
No local packages or working download links found for tensorflow>=1.0.0
**error: Could not find suitable distribution for Requirement.parse('tensorflow>=1.0.0')**

kindly help me to fix this

**Comment by nshmyrev** [comment]
Install systemwide
