### ISSUE TITLE
Why not use a dictionary?

### ISSUE THREAD

**Issue by StevenLOL** [cmusphinx/g2p-seq2seq#89]
Hi,

I got a novice question, why use this approach rather than looking up from dictionary ?  To handle OOV word ?

**Comment by brijmohan** [comment]
English does not have one-to-one grapheme (written token) to phoneme (spoken sound token) mapping. If that would be the case, we can simply write rules to convert words to their corresponding pronunciation. But there still exists a pattern which can be followed to convert sequence of characters to their corresponding sequence of phonemes. Therefore, seq2seq is a natural fit for G2P.

To answer your question, dictionary lookup is limited to a finite number of words. New words are added to vocabulary occasionally and language systems must know how to pronounce them.

**Comment by nshmyrev** [comment]
Nice answer @brijmohan

**Comment by StevenLOL** [comment]
Thanks @brijmohan

**Comment by brijmohan** [comment]
You're welcome :)
