### ISSUE TITLE
The ID of the symbol _UNK

### ISSUE THREAD

**Issue by yuyue9284** [cmusphinx/g2p-seq2seq#90]
Hi,
In g2p-seq2seq/g2p_seq2seq/g2p.py, line 120-121
```
# By default unk to unk
data_set = [[[[4], [4]]] for _ in self._BUCKETS]
```
shouldn't the id for unk be 3 instead of 4?

**Comment by nurtas-m** [comment]
Hello,
Yes, it's a mistake. Thank you very much! We will fix it.
