### ISSUE TITLE
Implement p2g mode

### ISSUE THREAD

**Issue by nshmyrev** [cmusphinx/g2p-seq2seq#92]
A command line option should allow to use this code in p2g mode where both letters and phonemes are split by spaces and both are split by some character like comma.

**Comment by virmht** [comment]
Hi! I wish to implement p2g mode. I have a couple a questions regarding the same:
1. Do I need to implement the p2g mode from scratch?
2. Is there any way to use the existing g2p code to implement p2g mode ?
3. How do you suggest to go about implementing this ?

**Comment by nshmyrev** [comment]
> Do I need to implement the p2g mode from scratch?

No, you just change data input, the model training is the same

> Is there any way to use the existing g2p code to implement p2g mode ?

You use most of the code, just make sure you are using latest t2t branch where all development happens.

> How do you suggest to go about implementing this ?

Learn how input data is processed and modify it to allow input of phone sequences instead of words. The model has to be trained separately of course.

**Comment by nshmyrev** [comment]
You'd better look on https://github.com/cmusphinx/g2p-seq2seq/issues/50 first.

**Comment by virmht** [comment]
Thank You!

**Comment by virmht** [comment]
Hello @nshmyrev , can you review my code and suggest further steps? You can see my PR [here](https://github.com/cmusphinx/g2p-seq2seq/pull/94).

**Comment by virmht** [comment]
Hey, @nshmyrev , the tests and hence, the build from t2t branch is failing, hence is it okay use the master branch for implementing the P2G mode? I have been using the master branch till now.

**Comment by nshmyrev** [comment]
> hence is it okay use the master branch for implementing the P2G mode?

Yes, absolutely

**Comment by virmht** [comment]
Hello! Please review my [PR](https://github.com/cmusphinx/g2p-seq2seq/pull/95).

**Comment by nshmyrev** [comment]
@virmht there is no need to create a new pull request each time. You just push to the branch in your repo and the pull request is updated automatically. Please close pull request #95 and properly update pull request #94.

**Comment by virmht** [comment]
Done, updated PR #94 and closed PR #95 .

**Comment by nshmyrev** [comment]
Merged

**Comment by nshmyrev** [comment]
We need to bring this feature back

**Comment by colibri17** [comment]
Any hope of having the feature back?

**Comment by nurtas-m** [comment]
Fixed with commit 05d4e6bb09a095824ce9d039b349e9d875d2dcba
