### ISSUE TITLE
Unable to install g2p-seq2seq

### ISSUE THREAD

**Issue by kushagraagrawal** [cmusphinx/g2p-seq2seq#96]
Hi, I was trying to install g2p-seq2seq on my system when it threw the following error:

`Searching for tensorflow>=1.0.0
Reading https://pypi.python.org/simple/tensorflow/
No local packages or working download links found for tensorflow>=1.0.0
error: Could not find suitable distribution for Requirement.parse('tensorflow>=1.0.0')`

However, I have tensorflow installed in my system and I verified the same: 
`pip list | grep tensorflow
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.8)`

Can someone please help me figuring out where am I going wrong? Apologies if this question is too basic, I am a beginner.

**Comment by nshmyrev** [comment]
Ask tensorflow support
