### ISSUE TITLE
license for pretrained model?

### ISSUE THREAD

**Issue by aparrish** [cmusphinx/g2p-seq2seq#98]
The license document in the repository presumably applies to the code. What license governs the use of the pre-trained model? Can I redistribute it?

**Comment by nshmyrev** [comment]
> What license governs the use of the pre-trained model? 

Same as the cmudict

> Can I redistribute it?

Sure, but I suggest you to wait for a week, we are going to release more accurate model based on updated t2t architecture, see the t2t branch
